_target_: stocbench.models.backbones.unet.UNetWrapper
in_channels: ${in:${oc.select:data.cond_len,1},${data.sim_channels},${data.sim_params},${oc.select:data.cond_extra_channels,0}}
out_channels: ${out:${data.sim_channels},${data.sim_params}}
hid_channels: 64
ch_multipliers: [1, 2, 2, 2]
num_res_blocks: 2
apply_attn: [false, true, false, false]
drop_rate: 0.1
resample_with_conv: true
padding_mode: circular  # zeros | circular | reflect | replicate
