wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: stocbench
  name: ${hydra:runtime.choices.model}_${now:%Y-%m-%d_%H-%M-%S}
  entity: ${oc.env:WANDB_ENTITY,null}
  log_model: false
  save_dir: .
  offline: false
